version: '3'

services:
  hubster:
    build: .
    volumes:
      - .:/opt/services/hubster/src
    env_file:
      - .env
    networks:
      - nginx_network
      - postgres_network
    depends_on:
      - postgres

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - hubster
    networks:
      - nginx_network

  postgres:
    image: postgres
    ports:
      - 1234:5432
    env_file:
      - .env
    networks:
      - postgres_network
    volumes:
      - database_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  database_volume:
