version: '3'

services:
  hubster:
    build: .
    volumes:
      - .:/opt/services/hubster/src
    networks:
      - nginx_network
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - hubster
    networks:
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
