# Generated by Django 2.2.1 on 2019-05-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar_url', models.URLField()),
                ('bio', models.TextField()),
                ('blog', models.URLField()),
                ('company', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('events_url', models.URLField()),
                ('followers', models.IntegerField()),
                ('followers_url', models.URLField()),
                ('following', models.IntegerField()),
                ('following_url', models.URLField()),
                ('gists_url', models.URLField()),
                ('gravatar_id', models.CharField(max_length=50)),
                ('hireable', models.BooleanField(default=False)),
                ('html_url', models.URLField()),
                ('location', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('node_id', models.SlugField()),
                ('organizations_url', models.URLField()),
                ('public_gists', models.IntegerField()),
                ('public_repos', models.IntegerField()),
                ('received_events_url', models.URLField()),
                ('repos_url', models.URLField()),
                ('site_admin', models.BooleanField(default=False)),
                ('starred_url', models.URLField()),
                ('subscriptions_url', models.URLField()),
                ('type', models.CharField(max_length=32)),
                ('updated_at', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
    ]
