# Generated by Django 2.2.1 on 2019-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubster', '0003_githubrepo_license_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='pushed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
