# Generated by Django 2.2.1 on 2019-05-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubster', '0004_auto_20190503_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='git_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='mirror_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='ssh_url',
            field=models.CharField(max_length=200),
        ),
    ]
