# Generated by Django 2.2.1 on 2019-05-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubster', '0006_auto_20190503_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='node_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='gravatar_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='node_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='license',
            name='node_id',
            field=models.CharField(max_length=12),
        ),
    ]
