# Generated by Django 2.2.1 on 2019-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubster', '0008_auto_20190503_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='blog',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='public_gists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='public_repos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
