# Generated by Django 2.2.1 on 2019-05-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubster', '0010_auto_20190505_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='mirror_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='network_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='stargazers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='subscribers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='watchers_count',
            field=models.IntegerField(default=0),
        ),
    ]
