# Generated by Django 2.2.1 on 2019-05-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubster', '0011_auto_20190506_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='homepage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='mirror_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
