# Generated by Django 2.2.1 on 2019-05-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubster', '0014_auto_20190506_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hubster.License'),
        ),
    ]
