# Generated by Django 2.2.1 on 2019-05-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubster', '0016_auto_20190506_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='spdx_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='license',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
